language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - GH_USER_EMAIL="travis@example.org"
    - GH_USER_NAME="cozy-bot"
    - DEPLOY_REPOSITORY="git@github.com:konnectors/netflix.git"
    # REGISTRY_TOKEN
    - secure: "JHtR4AHkqat/tsGfdqQzwO1fwcngA5choBPhf9BR5eq0IEOVfUxbxa2GNJsj9oWS2N3Em1s5n/WyVktPVrGB0G+ytow/3I8WPsZAVn1tN1YBJz/2JDUu8GB8X06DhXef8iZ4vVbbtQttTKiSWAZUmkiuCluLaI/Q5HRLnLUEzkYtVevSALAw78ZEDrZjwqPAN+admC6WnROyuyaysxOyviY94E64GKsWhdFW79zPWBLBldAEzw2BRyBparyl04trS5ksEmbzyDM/PSd+R73ooWnJ9SGjsaI/eThCbTsdMdtgAFI0tfDaRp8yg/a2jjdcGKHb6LJOVjzPtCpMLgv40CLJepyl9vjq0mEVh4Uay52meZrBQZrV71O5jxV2BYuZVKJ8M6brZD/2vtZM6wqv5VBci6PBAPRG0KrNGaX2Q7dDmOXjQFxq4w9UrsTmrQc3o8QOxrjFI3W986cRCHwLQgycP9BtrvMGGMKZl6VsodEezOPoLEdVMiPE4K5AMAt4JB9uPMEgFZCpl1iYn+mvB5BKTBkN2cJWnmrZupRzFGsxx825Q0zwKA8if/du369g/66k7KOhI6FetzG/ubysZeCqe45HVHl3Y7YuP4bJ9enw4qpGFGPB6b5Np7ovXvX1AiOzlwUlu7vlnBM0oRwhO8cNBDD6M4/2u/z9vNomAfw="
script:
  - yarn lint
  - yarn build
deploy:
  # publish dev versions
  - provider: script
    skip-cleanup: true
    script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
    on:
      branch: master
  # publish on latest branch (will be removed when collect will use only the registry
  - provider: script
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
  # publish stable versions and beta versions based on tags
  - provider: script
    skip-cleanup: true
    script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
    on:
      tags: true
before_install:
  - openssl aes-256-cbc -K $encrypted_b13dddac253b_key -iv $encrypted_b13dddac253b_iv -in github_deploy_key.enc -out github_deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/github_deploy_key
  - ssh-add /tmp/github_deploy_key
